CybertownRevival/ctr

.gitignore
api/api/controllers/member.js
api/api/libs/mail.js
api/api/routes/member.js
api/package-lock.json
api/package.json
docker-compose.yml
spa/package-lock.json
spa/src/api.js
spa/src/main.js
spa/src/pages/ForgotPasswordPage.vue
spa/src/pages/PasswordResetPage.vue
spa/src/routes.js

16 password reset

---

spa/package-lock.json
spa/package.json

Committing the results of an `npm audit fix`. Fixed 11 critical vulnerabilities by updating socket.io.

npm audit fixes - updated socket.io

---

spa/src/components/Chat.vue

Change log:
- Changed Chat.vue to have 3D icon populate for each user instead of 2D icon

3D Icon Fix

---

api/src/controllers/member.controller.ts
api/src/controllers/object-instance.controller.ts
api/src/controllers/place.controller.ts

The errors for login page were being sent just were not properly jsonify'ed
Corrects #105

Convert error message to json format

---

api/repl.ts
api/src/repositories/member/member.repository.ts
api/tsconfig.prod.json

136 reset token bug

---

api/src/controllers/home.controller.ts
spa/src/assets/index.scss
spa/src/components/place/home/main2d.vue
spa/src/pages/block/BlockMovePage.vue
spa/src/pages/home/HomeUpdateHomePage.vue
spa/src/pages/world-browser/WorldBrowserPage.vue
spa/src/pages/world-browser/world-browser-data.interface.ts

resolves #167 , resolves #166 , resoles #165 
* reformatted settle and update home pages to match correct styling of original

#166 fix non-3d homes, force 2d icon requirement

---

spa/src/components/Chat.vue
spa/src/pages/world-browser/WorldBrowserPage.vue

Click a user in the list to beam to them.
Does not currently respect SharedZone.beamToViewpoint, and SharedZone.beamToDistance support was written but is untested.
May not have ideal results when beaming to someone who is in 2D.

Beam to. Fixes #141

---

api/src/controllers/home.controller.ts
spa/src/pages/home/HomeUpdateHomePage.vue

Home Update

---

api/src/controllers/home.controller.ts
spa/src/pages/home/HomeUpdateHomePage.vue

Reverts CybertownRevival/ctr#239

Revert "Home Update"

---

api/src/controllers/home.controller.ts
api/src/repositories/home-design/home-design.repository.ts
api/src/services/home/home.service.ts

Home bug fix

---

api/src/controllers/mall.controller.ts
api/src/services/object/object.service.ts
spa/src/pages/mall/MallRulesPage.vue
spa/src/pages/mall/staff/StaffPage.vue

Updated mall rule to allow up to 5 different color/texture variations on a model rather than 3.
Fixed a bug that caused items to not show up in the store they were dropped in randomly.
Added delay to loading the data in the warehouse when an item was dropped.

Update Mall Rule & Bug Fix

---

api/src/controllers/object.controller.ts
api/src/services/object/object.service.ts
spa/server.js
spa/src/components/Chat.vue
spa/src/pages/ObjectProperties.vue
spa/src/pages/mall/MallUploadPage.vue
spa/src/pages/mall/creator/CreatorPage.vue

Added GIF and PNG images to the list of accepted file-types for textures that can be uploaded to the mall. Added ability for creators to add quantities to objects that are still dropped in the mall.

Mall Update

---

api/src/controllers/object.controller.ts
api/src/services/object/object.service.ts
spa/server.js
spa/src/components/Chat.vue
spa/src/pages/ObjectProperties.vue
spa/src/pages/mall/MallUploadPage.vue
spa/src/pages/mall/creator/CreatorPage.vue

Reverts CybertownRevival/ctr#277

Revert "Mall Update"

---

api/src/controllers/member.controller.ts
api/src/services/member/member.service.ts
api/src/types/views/member-info.view.interface.ts
spa/src/components/place/home/main2d.vue

Added users last access date to homes and removed the commented section that was a place holder.

Added users last access to homes

---

spa/src/components/Chat.vue

Resolves issue #284 
Updated to make the chat input the focus when chat loads.

Resolves Issue #284: Update Chat

---

api/src/repositories/object/object.repository.ts
spa/src/pages/mall/creator/restock.vue

Fixed restockable page to show the correct objects. Fixed mall object search for staff page to only show approved objects.

Fix Creator Page

---

spa/src/components/Chat.vue
spa/src/pages/ObjectProperties.vue
spa/src/pages/world-browser/WorldBrowserPage.vue

Updated methods to allow object lists to update properly when an object instance is purchased from a backpack or public objects.

Update Object Instance

---

spa/src/components/Chat.vue
spa/src/pages/mall/creator/catalog.vue
spa/src/pages/mall/creator/pending.vue
spa/src/pages/mall/creator/restock.vue
spa/src/pages/mall/creator/stocked.vue

Fix creator page pagination

---

api/src/controllers/mall.controller.ts
api/src/repositories/object/object.repository.ts
api/src/services/mall/mall.service.ts
spa/src/pages/mall/staff/pending.vue
spa/src/pages/mall/staff/search.vue
spa/src/pages/mall/staff/soldout.vue
spa/src/pages/mall/staff/stocked.vue
spa/src/pages/mall/staff/warehouse.vue

Fixed mall staff page pagination and gave more options for sorting the lists.

Fix mall staff pagination

---

spa/src/pages/mall/MallRulesPage.vue

Fix typos that were in the mall rules.

Fix mall rules typos

---

spa/src/components/Chat.vue

Fix what buttons come up in the public places for admin

Update Click-Menu Buttons

---

api/src/controllers/admin.controller.ts
api/src/repositories/place/place.repository.ts
api/src/routes/admin.routes.ts
api/src/services/place/place.service.ts
spa/src/pages/admin/place/search.vue

Updated the way place search functions.

Improve Admin Place Search

---

api/src/routes/object.routes.ts
spa/src/pages/mall/checker.vue

Fixed the loading of the objects on the mall staff page.

Fix Checker

---

api/src/controllers/member.controller.ts
api/src/repositories/member/member.repository.ts
api/src/routes/member.routes.ts
api/src/services/member/member.service.ts
spa/server.js
spa/src/App.vue
spa/src/components/Chat.vue
spa/src/components/modals/CitizenOnlineModal.vue
spa/src/components/modals/ConfigureModal.vue
spa/src/components/modals/ConfirmAlertModal.vue
spa/src/components/modals/InstantMessageModal.vue
spa/src/components/modals/MemberModal.vue
spa/src/components/modals/Modal.vue
spa/src/components/modals/MyMessagesModal.vue
spa/src/components/modals/SecurityAlertModal.vue

Adding citizens online list feature.

Adding Citizens Online List

---

api/src/controllers/admin.controller.ts
api/src/controllers/mall.controller.ts
api/src/repositories/object/object.repository.ts
api/src/routes/admin.routes.ts
api/src/routes/mall.routes.ts
api/src/services/admin/admin.services.ts
api/src/services/mall/mall.service.ts
spa/src/pages/admin/admin.vue
spa/src/pages/admin/objects/search.vue
spa/src/pages/admin/objects/update.vue
spa/src/routes.ts

Adding object search tool to the admin panel.

Object Search Tool

---

api/src/services/place/place.service.ts

Added owner username to be displayed on the place search where relevant.

Update Place Search

---

api/src/controllers/member.controller.ts
api/src/routes/member.routes.ts
spa/src/components/Chat.vue

Updated the method that was used to detect if a user was 3D or not.

Fix AVs Loading

---

spa/src/components/Chat.vue
spa/src/pages/mall/creator/restock.vue

Adding text to speech feature on chat. Feature off by default, but can be toggled on by the user. Resolves issue #6

Add text to speech feature

---

api/src/controllers/place.controller.ts
api/src/repositories/place/place.repository.ts
api/src/routes/place.routes.ts
api/src/services/place/place.service.ts
spa/src/components/storage/Storage.vue
spa/src/components/storage/Unit.vue
spa/src/components/storage/Update.vue

Made storage areas with no name visible, removed the ability to update the storage name to an empty value, and added feature to allow people to delete storage areas. Resolves issue #340

Update Storage Area

---

api/src/repositories/member/member.repository.ts

Order online list by username.

Order Online LIst

---

api/src/repositories/message/message.repository.ts
api/src/repositories/messageboard/messageboard.repository.ts
api/src/repositories/object-instance/object-instance.repository.ts
api/src/services/admin/admin.services.ts
spa/src/main.ts
spa/src/pages/admin/overview/panels/data.vue
spa/src/pages/club/ClubDoor.vue
spa/src/pages/club/Members.vue

Fixing some bugs in clubs access.

Update Club Access

---

spa/src/pages/home/HomeVirtualPet.vue

Fixes bug when viewing page on a mobile device.

Fix Update Pet View

---

api/src/controllers/inbox.controller.ts
api/src/controllers/messageboard.controller.ts
api/src/repositories/inbox/inbox.repository.ts
api/src/repositories/messageboard/messageboard.repository.ts
api/src/routes/inbox.routes.ts
api/src/routes/messageboard.routes.ts
api/src/services/inbox/inbox.service.ts
api/src/services/messageboard/messageboard.service.ts
spa/src/pages/InboxToAll.vue
spa/src/pages/MessageToAll.vue
spa/src/pages/block/BlockTools.vue
spa/src/pages/neighborhood/NeighborhoodTools.vue
spa/src/pages/world-browser/WorldBrowserTools.vue
spa/src/routes.ts

Added api and spa to support message and inbox all tool in the colonies.

Add functionality for posting messages to all and inbox to all

---

spa/src/pages/ObjectProperties.vue

Fixes objects disappearing from lists. Object names must contain a valid visible character and not contain only spaces. Also added the ability to use underscore and periods in the name of the object. Also updated so that the buyer listed does not have to be case-sensitive for the intended user to buy the object.

Fix Object Naming Bug

---

api/src/controllers/block.controller.ts
api/src/controllers/colony.controller.ts
api/src/controllers/hood.controller.ts
api/src/controllers/place.controller.ts
api/src/services/place/place.service.ts

Fixed issue with variable names.

Fix Access Bug
